### ISSUE TITLE
Switch to regex-based matching to allow for context matches

### ISSUE THREAD

**Issue by Alpvax** [Dotnaught/Spellerizer#1]
As stated in your article, currently you just replace "check" with "cheque" because you are only operating on individual words.
If you replaced the check match with `((a|the)\s)?check` then you would match "a check" or "the check", and you would just have to replace it with '\1cheque` (although you might want to replace the central section manually to case match it). You could also add a `check( please)` match.
You could alternatively specify it in the JSON as a context prefix/suffix where you would specify it as a regex (and when building the actual regex, add the case insensitive flag and probably lookahead/look behind so the context matched could also be replaced if needed.

I am using check as an example, I'm sure that there are other words that would benefit from context matching.

Edit: I have just read your article further, and noticed that the spelling_data.json file was not written by you and this would require changes to that file / format

**Comment by Dotnaught** [comment]
Thanks for the suggestion. Unfortunately, crafting a different regex for handling every homonym in the ~1,700 word database (many dozens at least) would be a lot of work. I'd consider pull requests if they're demonstrable effective but this isn't an addition I plan to undertake for now.

**Comment by Alpvax** [comment]
Yeah, that's understandable. I wasn't suggesting that you do it all at once, but if you made the switch then others could pr in different words/contexts. I also didn't register that there were that many words in the list, I only looked at the first few.
For what the extension does, you're right, it's probably not really worth the additional effort
